---
- name: Remover usuário do Active Directory via AWX
  hosts: ad_server
  gather_facts: no
  collections:
    - microsoft.ad

  vars:
    nome_usuario: ""   # Vai vir do survey do AWX

  tasks:
    - name: Remover usuário informado
      microsoft.ad.user:
        name: "{{ nome_usuario }}"
        state: absent
